name: Build and Deploy

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: source

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mdbook

    - name: Build the HTML
      run: |
        ./build.sh

    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    # - name: Copy book to main branch
    #   run: |
    #     cp -r book/* .

    - name: Commit and push to main branch
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'githubaction@users.noreply.github.com'
        git add -A
        git commit -m "Update from GitHub Action"
        git push origin main